version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.1
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.0
    - 2.8.1
  - dependency-name: pytest
    versions:
    - 6.2.2
